apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 3001   # External Port
    targetPort: 3000  # Fix: Matches Grafana container port
    nodePort: 32439
    protocol: TCP
  selector:
    app: grafana
